server:
  port: 8080

logging:
  file:
    name: mylog.log
    path: logs

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:3306/course
    username: root
    password: root
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*